//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Email {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("<!DOCTYPE html>\r\n\r\n<html lang=\"en\" xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r" +
            "\n    <meta charset=\"utf-8\" />\r\n    <title></title>\r\n</head>\r\n<body>\r\n    <div id" +
            "=\":u8\" class=\"ii gt\">\r\n        <div id=\":u7\" class=\"a3s aXjCH \">\r\n            <d" +
            "iv>\r\n                <div>\r\n                    <table align=\"center\" bgcolor=\"#" +
            "ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" style=\"font-family:Helvetica " +
            "neue,Helvetica,Arial,Verdana,sans-serif\" width=\"100%\">\r\n                        " +
            "<tr>\r\n                            <td colspan=\"1\" rowspan=\"1\">\r\n                " +
            "                <table align=\"center\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"" +
            "0\" cellspacing=\"0\" width=\"520px\">\r\n                                    <tr>\r\n   " +
            "                                     <td colspan=\"1\" rowspan=\"1\" valign=\"top\">\r\n" +
            "                                            <table bgcolor=\"#ffffff\" border=\"0\" " +
            "cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n                                 " +
            "               <tr>\r\n                                                    <td ali" +
            "gn=\"left\" colspan=\"1\" rowspan=\"1\" style=\"color:#05AFF2; font-size:20px;line-heig" +
            "ht:32px;text-align:left;font-weight:bold\" valign=\"top\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span>@Do" +
            "cType @SerNumCor</span>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t</td>\r\n                                   " +
            "             </tr>\r\n                                                <tr>\r\n      " +
            "                                              <td colspan=\"1\" rowspan=\"1\" style=" +
            "\"color:#05AFF2;padding-bottom:15px\" valign=\"top\">\r\n                             " +
            "                           <hr color=\"#cccccc\" size=\"1\" />\r\n                    " +
            "                                </td>\r\n                                         " +
            "       </tr>\r\n                                                <tr align=\"left\" c" +
            "olspan=\"1\" rowspan=\"1\" valign=\"top\">\r\n                                          " +
            "          <td>\r\n                                                        <div sty" +
            "le=\"padding:10px 0; background-color: #05AFF2; color: white;\">\r\n                " +
            "                                            <p style=\"padding:0 30px\">Estimados " +
            "@NomSocNeg</p>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n                                          " +
            "          </td>\r\n                                                </tr>\r\n        " +
            "                                        <tr align=\"left\" colspan=\"1\" rowspan=\"1\"" +
            " valign=\"top\">\r\n                                                    <td>\r\n      " +
            "                                                  <div style=\"padding:10px 30px;" +
            " color: #0D1826;\">\r\n                                                            " +
            "Se adjunta en este mensaje una @DocType\r\n                                       " +
            "                 </div>\r\n                                                    </t" +
            "d>\r\n                                                </tr>\r\n                     " +
            "                           <tr align=\"left\" colspan=\"1\" rowspan=\"1\" valign=\"top\"" +
            ">\r\n                                                    <td>\r\n                   " +
            "                                     <div style=\"padding:5px 0\">\r\n              " +
            "                                              <ul>\r\n                            " +
            "                                    <li><b>@DocType @SerNumCor </b></li>\r\n      " +
            "                                                          <li>Fecha de emisión: " +
            "<b>@FecEmi</b></li>\r\n                                                           " +
            "     <li>Total: <b>S/ @TotDoc</b></li>\r\n                                        " +
            "                    </ul>\r\n                                                     " +
            "   </div>\r\n                                                        <div style=\"p" +
            "adding:5px 30px; color: #0D1826;\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<p>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tSe adjun" +
            "ta en este mensaje el documento electrónico en formatos PDF y XML. La representa" +
            "ción impresa en PDF tiene la misma validez que una emitida de manera tradicional" +
            ".\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</p>\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\r\n                                  " +
            "                      <div style=\"padding:5px 30px; background-color: #F2A413; c" +
            "olor: white;\">\r\n                                                            Repr" +
            "esentación impresa de la @DocType generada desde el sistema facturador SUNAT. Pu" +
            "ede verificarla utilizando su clave SOL<br />\r\n                                 " +
            "                           <br />\r\n                                             " +
            "               <a href=\"https://e-consulta.sunat.gob.pe/ol-ti-itconsvalicpe/Cons" +
            "ValiCpe.htm\">https://e-consulta.sunat.gob.pe/ol-ti-itconsvalicpe/ConsValiCpe.htm" +
            "</a></div>\r\n                                                    </td>\r\n         " +
            "                                       </tr>\r\n                                  " +
            "              <tr align=\"left\" colspan=\"1\" rowspan=\"1\" valign=\"top\">\r\n          " +
            "                                          <td>\r\n                                " +
            "                        <div style=\"padding:0 30px\">\r\n                          " +
            "                                  <table bgcolor=\"#ffffff\" border=\"0\" cellpaddin" +
            "g=\"0\" cellspacing=\"0\" width=\"100%\">\r\n                                           " +
            "                     <tr valign=\"top\">\r\n                                        " +
            "                            <td align=\"left\" colspan=\"1\" rowspan=\"1\" style=\"padd" +
            "ing-top:10px;text-align:left; color: #0D1826;\" valign=\"top\">\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t" +
            "<span>Atentamente</span>:<br clear=\"none\" />\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t@RazSoc<br cle" +
            "ar=\"none\" />\r\n                                                                  " +
            "      <span><b>RUC @Ruc</b></span><br clear=\"none\" />\r\n                         " +
            "                                               <br />\r\n                         " +
            "                                           </td>\r\n                              " +
            "                                  </tr>\r\n                                       " +
            "                     </table>\r\n                                                 " +
            "       </div>\r\n                                                    </td>\r\n      " +
            "                                          </tr>\r\n                               " +
            "                 <tr>\r\n                                                    <td c" +
            "olspan=\"1\" rowspan=\"1\">\r\n                                                       " +
            " <table align=\"center\" bgcolor=\"#ffffff\" border=\"0\" cellpadding=\"0\" cellspacing=" +
            "\"0\" width=\"100%\">\r\n                                                            <" +
            "tr>\r\n                                                                <td colspan" +
            "=\"1\" rowspan=\"1\" style=\"color:white; text-align: center; font-size: small; backg" +
            "round-color: #0D1826;\" valign=\"top\" width=\"100%\">\r\n                             " +
            "                                       TaGre-System<br />\r\n                     " +
            "                                               993433774</td>\r\n                 " +
            "                                           </tr>\r\n                              " +
            "                              <tr>\r\n                                            " +
            "                    <td colspan=\"1\" rowspan=\"1\">\r\n                              " +
            "                                      <div>\r\n                                   " +
            "                                     <table align=\"center\" bgcolor=\"#ffffff\" bor" +
            "der=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">\r\n                         " +
            "                                                   <tr>\r\n                       " +
            "                                                         <td align=\"left\" colspa" +
            "n=\"1\" rowspan=\"1\" style=\"padding-top:10px;color:#707070;font-size:12px;line-heig" +
            "ht:14px;text-align:left\" valign=\"top\">\r\n                                        " +
            "                                            <br clear=\"none\" />\r\n               " +
            "                                                                 </td>\r\n        " +
            "                                                                    </tr>\r\n     " +
            "                                                                   </table>\r\n   " +
            "                                                                 </div>\r\n       " +
            "                                                         </td>\r\n                " +
            "                                            </tr>\r\n                             " +
            "                           </table>\r\n                                           " +
            "         </td>\r\n                                                </tr>\r\n         " +
            "                                   </table>\r\n                                   " +
            "     </td>\r\n                                    </tr>\r\n                         " +
            "       </table>\r\n                            </td>\r\n                        </tr" +
            ">\r\n                    </table>\r\n                    <div class=\"yj6qo\">\r\n      " +
            "              </div>\r\n                    <div class=\"adL\">\r\n                   " +
            " </div>\r\n                </div>\r\n                <div class=\"adL\">\r\n            " +
            "    </div>\r\n                <div class=\"adL\">\r\n                </div>\r\n         " +
            "       <div class=\"adL\">\r\n                </div>\r\n            </div>\r\n        </" +
            "div>\r\n    </div>\r\n    <div id=\":uz\" class=\"hq gt\">\r\n        <div class=\"hp\">\r\n  " +
            "      </div>\r\n    </div>\r\n</body>\r\n</html>\r\n")]
        public string CuerpoCorreo {
            get {
                return ((string)(this["CuerpoCorreo"]));
            }
            set {
                this["CuerpoCorreo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("cvjuan270@gmail.com")]
        public string UsuarioSMTP {
            get {
                return ((string)(this["UsuarioSMTP"]));
            }
            set {
                this["UsuarioSMTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("smtp.gmail.com")]
        public string ServidorSMTP {
            get {
                return ((string)(this["ServidorSMTP"]));
            }
            set {
                this["ServidorSMTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("587")]
        public int PuertoSMTP {
            get {
                return ((int)(this["PuertoSMTP"]));
            }
            set {
                this["PuertoSMTP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gmail161290270")]
        public string PassUsuaSMTP {
            get {
                return ((string)(this["PassUsuaSMTP"]));
            }
            set {
                this["PassUsuaSMTP"] = value;
            }
        }
    }
}
