//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFS_ASP_1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SEGURIMAX02Entities : DbContext
    {
        public SEGURIMAX02Entities()
            : base("name=SEGURIMAX02Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<OINV> OINV { get; set; }
        public virtual DbSet<NNM1> NNM1 { get; set; }
        public virtual DbSet<ODLN> ODLN { get; set; }
        public virtual DbSet<ORIN> ORIN { get; set; }
    
        public virtual int Actualizar_Rpta_Cdr(Nullable<int> docentry, string u_ResponseCode, string u_Description, string u_DigestValue)
        {
            var docentryParameter = docentry.HasValue ?
                new ObjectParameter("Docentry", docentry) :
                new ObjectParameter("Docentry", typeof(int));
    
            var u_ResponseCodeParameter = u_ResponseCode != null ?
                new ObjectParameter("U_ResponseCode", u_ResponseCode) :
                new ObjectParameter("U_ResponseCode", typeof(string));
    
            var u_DescriptionParameter = u_Description != null ?
                new ObjectParameter("U_Description", u_Description) :
                new ObjectParameter("U_Description", typeof(string));
    
            var u_DigestValueParameter = u_DigestValue != null ?
                new ObjectParameter("U_DigestValue", u_DigestValue) :
                new ObjectParameter("U_DigestValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_Rpta_Cdr", docentryParameter, u_ResponseCodeParameter, u_DescriptionParameter, u_DigestValueParameter);
        }
    
        public virtual int Actualizar_Rpta_Cdr_GR(Nullable<int> docentry, string u_ResponseCode, string u_Description, string u_DigestValue)
        {
            var docentryParameter = docentry.HasValue ?
                new ObjectParameter("Docentry", docentry) :
                new ObjectParameter("Docentry", typeof(int));
    
            var u_ResponseCodeParameter = u_ResponseCode != null ?
                new ObjectParameter("U_ResponseCode", u_ResponseCode) :
                new ObjectParameter("U_ResponseCode", typeof(string));
    
            var u_DescriptionParameter = u_Description != null ?
                new ObjectParameter("U_Description", u_Description) :
                new ObjectParameter("U_Description", typeof(string));
    
            var u_DigestValueParameter = u_DigestValue != null ?
                new ObjectParameter("U_DigestValue", u_DigestValue) :
                new ObjectParameter("U_DigestValue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_Rpta_Cdr_GR", docentryParameter, u_ResponseCodeParameter, u_DescriptionParameter, u_DigestValueParameter);
        }
    
        public virtual int Actualizar_Rpta_Cdr_NC(Nullable<int> docentry, string u_ResponseCode, string u_Description)
        {
            var docentryParameter = docentry.HasValue ?
                new ObjectParameter("Docentry", docentry) :
                new ObjectParameter("Docentry", typeof(int));
    
            var u_ResponseCodeParameter = u_ResponseCode != null ?
                new ObjectParameter("U_ResponseCode", u_ResponseCode) :
                new ObjectParameter("U_ResponseCode", typeof(string));
    
            var u_DescriptionParameter = u_Description != null ?
                new ObjectParameter("U_Description", u_Description) :
                new ObjectParameter("U_Description", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Actualizar_Rpta_Cdr_NC", docentryParameter, u_ResponseCodeParameter, u_DescriptionParameter);
        }
    
        public virtual ObjectResult<Consulta_Datos_Generales_Result> Consulta_Datos_Generales()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_Datos_Generales_Result>("Consulta_Datos_Generales");
        }
    
        public virtual ObjectResult<Consulta_Datos_Reporte_GR_Result> Consulta_Datos_Reporte_GR(Nullable<int> docEntry)
        {
            var docEntryParameter = docEntry.HasValue ?
                new ObjectParameter("DocEntry", docEntry) :
                new ObjectParameter("DocEntry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_Datos_Reporte_GR_Result>("Consulta_Datos_Reporte_GR", docEntryParameter);
        }
    
        public virtual ObjectResult<Consulta_DatosCorreo_Result> Consulta_DatosCorreo(Nullable<int> docEntry)
        {
            var docEntryParameter = docEntry.HasValue ?
                new ObjectParameter("DocEntry", docEntry) :
                new ObjectParameter("DocEntry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_DatosCorreo_Result>("Consulta_DatosCorreo", docEntryParameter);
        }
    
        public virtual ObjectResult<Consulta_factura_DetalleCR_Result> Consulta_factura_DetalleCR(Nullable<int> docNum)
        {
            var docNumParameter = docNum.HasValue ?
                new ObjectParameter("DocNum", docNum) :
                new ObjectParameter("DocNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_factura_DetalleCR_Result>("Consulta_factura_DetalleCR", docNumParameter);
        }
    
        public virtual ObjectResult<Consulta_factura_EncabezadoCR_Result> Consulta_factura_EncabezadoCR(Nullable<int> docNum)
        {
            var docNumParameter = docNum.HasValue ?
                new ObjectParameter("DocNum", docNum) :
                new ObjectParameter("DocNum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_factura_EncabezadoCR_Result>("Consulta_factura_EncabezadoCR", docNumParameter);
        }
    
        public virtual ObjectResult<Consulta_GuiasRemision_Result> Consulta_GuiasRemision(Nullable<System.DateTime> fECINI, Nullable<System.DateTime> fECFIN)
        {
            var fECINIParameter = fECINI.HasValue ?
                new ObjectParameter("FECINI", fECINI) :
                new ObjectParameter("FECINI", typeof(System.DateTime));
    
            var fECFINParameter = fECFIN.HasValue ?
                new ObjectParameter("FECFIN", fECFIN) :
                new ObjectParameter("FECFIN", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_GuiasRemision_Result>("Consulta_GuiasRemision", fECINIParameter, fECFINParameter);
        }
    
        public virtual ObjectResult<Consulta_SFS_ACA_Result> Consulta_SFS_ACA(Nullable<int> docEntry)
        {
            var docEntryParameter = docEntry.HasValue ?
                new ObjectParameter("DocEntry", docEntry) :
                new ObjectParameter("DocEntry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_SFS_ACA_Result>("Consulta_SFS_ACA", docEntryParameter);
        }
    
        public virtual ObjectResult<Consulta_SFS_ACA_NC_Result> Consulta_SFS_ACA_NC(Nullable<int> docEntry)
        {
            var docEntryParameter = docEntry.HasValue ?
                new ObjectParameter("DocEntry", docEntry) :
                new ObjectParameter("DocEntry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_SFS_ACA_NC_Result>("Consulta_SFS_ACA_NC", docEntryParameter);
        }
    
        public virtual ObjectResult<Consulta_SFS_CAB_Result> Consulta_SFS_CAB(Nullable<int> docEntry)
        {
            var docEntryParameter = docEntry.HasValue ?
                new ObjectParameter("DocEntry", docEntry) :
                new ObjectParameter("DocEntry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_SFS_CAB_Result>("Consulta_SFS_CAB", docEntryParameter);
        }
    
        public virtual ObjectResult<Consulta_SFS_CAB_GR_Result> Consulta_SFS_CAB_GR(Nullable<int> docEntry)
        {
            var docEntryParameter = docEntry.HasValue ?
                new ObjectParameter("DocEntry", docEntry) :
                new ObjectParameter("DocEntry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_SFS_CAB_GR_Result>("Consulta_SFS_CAB_GR", docEntryParameter);
        }
    
        public virtual ObjectResult<Consulta_SFS_CAB_NC_Result> Consulta_SFS_CAB_NC(Nullable<int> docEntry)
        {
            var docEntryParameter = docEntry.HasValue ?
                new ObjectParameter("DocEntry", docEntry) :
                new ObjectParameter("DocEntry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_SFS_CAB_NC_Result>("Consulta_SFS_CAB_NC", docEntryParameter);
        }
    
        public virtual ObjectResult<Consulta_SFS_DET_Result> Consulta_SFS_DET(Nullable<int> docEntry)
        {
            var docEntryParameter = docEntry.HasValue ?
                new ObjectParameter("DocEntry", docEntry) :
                new ObjectParameter("DocEntry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_SFS_DET_Result>("Consulta_SFS_DET", docEntryParameter);
        }
    
        public virtual ObjectResult<Consulta_SFS_DET_GR_Result> Consulta_SFS_DET_GR(Nullable<int> docEntry)
        {
            var docEntryParameter = docEntry.HasValue ?
                new ObjectParameter("DocEntry", docEntry) :
                new ObjectParameter("DocEntry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_SFS_DET_GR_Result>("Consulta_SFS_DET_GR", docEntryParameter);
        }
    
        public virtual ObjectResult<Consulta_SFS_DET_NC_Result> Consulta_SFS_DET_NC(Nullable<int> docEntry)
        {
            var docEntryParameter = docEntry.HasValue ?
                new ObjectParameter("DocEntry", docEntry) :
                new ObjectParameter("DocEntry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_SFS_DET_NC_Result>("Consulta_SFS_DET_NC", docEntryParameter);
        }
    
        public virtual ObjectResult<Consulta_SFS_LEY_Result> Consulta_SFS_LEY(Nullable<int> docEntry)
        {
            var docEntryParameter = docEntry.HasValue ?
                new ObjectParameter("DocEntry", docEntry) :
                new ObjectParameter("DocEntry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_SFS_LEY_Result>("Consulta_SFS_LEY", docEntryParameter);
        }
    
        public virtual ObjectResult<Consulta_SFS_LEY_NC_Result> Consulta_SFS_LEY_NC(Nullable<int> docEntry)
        {
            var docEntryParameter = docEntry.HasValue ?
                new ObjectParameter("DocEntry", docEntry) :
                new ObjectParameter("DocEntry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_SFS_LEY_NC_Result>("Consulta_SFS_LEY_NC", docEntryParameter);
        }
    
        public virtual ObjectResult<Consulta_SFS_TRY_Result> Consulta_SFS_TRY(Nullable<int> docEntry)
        {
            var docEntryParameter = docEntry.HasValue ?
                new ObjectParameter("DocEntry", docEntry) :
                new ObjectParameter("DocEntry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_SFS_TRY_Result>("Consulta_SFS_TRY", docEntryParameter);
        }
    
        public virtual ObjectResult<Consulta_SFS_TRY_NC_Result> Consulta_SFS_TRY_NC(Nullable<int> docEntry)
        {
            var docEntryParameter = docEntry.HasValue ?
                new ObjectParameter("DocEntry", docEntry) :
                new ObjectParameter("DocEntry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Consulta_SFS_TRY_NC_Result>("Consulta_SFS_TRY_NC", docEntryParameter);
        }
    
        public virtual ObjectResult<Get_Tipo_NC_Result> Get_Tipo_NC(Nullable<int> docEntry)
        {
            var docEntryParameter = docEntry.HasValue ?
                new ObjectParameter("DocEntry", docEntry) :
                new ObjectParameter("DocEntry", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Get_Tipo_NC_Result>("Get_Tipo_NC", docEntryParameter);
        }

        
    }
}
