//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SFS_ASP_1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NNM1
    {
        public string ObjectCode { get; set; }
        public short Series { get; set; }
        public string SeriesName { get; set; }
        public Nullable<int> InitialNum { get; set; }
        public Nullable<int> NextNumber { get; set; }
        public Nullable<int> LastNum { get; set; }
        public string BeginStr { get; set; }
        public string EndStr { get; set; }
        public string Remark { get; set; }
        public Nullable<short> GroupCode { get; set; }
        public string Locked { get; set; }
        public string YearTransf { get; set; }
        public string Indicator { get; set; }
        public string Template { get; set; }
        public Nullable<int> NumSize { get; set; }
        public string FolioPref { get; set; }
        public Nullable<int> NextFolio { get; set; }
        public string DocSubType { get; set; }
    }
}
